const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "shirts",
      image: "/Images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "shirts",
      image: "/Images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Lazy Shirt",
      slug: "lazy-shirt",
      category: "shirts",
      image: "/Images/shirt3.jpg",
      price: 90,
      brand: "Puma",
      rating: 4.3,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "pants",
      image: "/Images/pants1.jpg",
      price: 40,
      brand: "puma",
      rating: 4.7,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pant",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "pants",
      image: "/Images/pants2.jpg",
      price: 50,
      brand: "Adidas",
      rating: 4.1,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pant",
    },
    {
      name: "Biker Pants",
      slug: "biker-pants",
      category: "zara",
      image: "/Images/pants3.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pant",
    },
  ],
};

export default data;
