const data = {
  products: [
    {
      name: "Free Shirt",
      category: "shirts",
      image: "/image/shirt1/jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      category: "shirts",
      image: "/image/shirt2/jpg",
      price: 80,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Lazy Shirt",
      category: "shirts",
      image: "/image/shirt3/jpg",
      price: 90,
      brand: "Puma",
      rating: 4.3,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Pants",
      category: "pants",
      image: "/image/pant1/jpg",
      price: 40,
      brand: "puma",
      rating: 4.7,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pant",
    },
    {
      name: "Golf Pants",
      category: "pants",
      image: "/image/pant2/jpg",
      price: 50,
      brand: "Adidas",
      rating: 4.1,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pant",
    },
    {
      name: "Biker Pants",
      category: "zara",
      image: "/image/pant3/jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pant",
    },
  ],
};
